import React, { useState } from "react";

export default function Bai7() {
  const [text, setText] = useState<string>("");
  const handleCHange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setText(e.target.value);
  }
  return <div style={{display: "flex", flexDirection: "column"}}>
    <select defaultValue={"--Chọn thành phố--"} onChange={handleCHange} id="option"> 
        <option>--Chọn thành phố--</option>
        <option>Ninh Bình</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
        <option>Thanh Hóa</option>
    </select>
    <span>Thành phố: {text === "--Chọn thành phố--" ? "": text}</span>
  </div>;
}